### Numpy random package

In [11]:
from numpy import random
print(random.randint(1,100))
print(random.rand())#float pt numbr b/w 0-1

13
0.2959628418686644


In [12]:
#generating n-d random arrays 
print(random.randint(100,size=(3)))
print(random.randint(100,size=(3,4)))
print(random.randint(100,size=(3,4,2)))

[18 40 94]
[[45  2 92 54]
 [25 91 18 77]
 [20 76 26 88]]
[[[22 43]
  [11 86]
  [65 14]
  [28 26]]

 [[36 89]
  [85 11]
  [99 20]
  [15 56]]

 [[71 64]
  [91 83]
  [36 89]
  [51 30]]]


In [13]:
#creating n-d arrays with floating values using random
print(random.rand())
print(random.rand(3))
print(random.rand(2,3))

0.06798102166438513
[0.26959643 0.10117754 0.50402993]
[[0.29107443 0.58209653 0.87477056]
 [0.58252866 0.7313888  0.13532338]]


In [14]:
a = random.randint(100,size=(3,2)).raval()
a

AttributeError: 'numpy.ndarray' object has no attribute 'raval'

In [15]:
random.choice(a)

NameError: name 'a' is not defined

In [16]:
random.choice([1,2,3,4,5],size=(4,4))

array([[4, 3, 5, 3],
       [5, 3, 4, 3],
       [2, 3, 5, 3],
       [2, 4, 1, 5]])

# Pandas:
1. Data manipulaion,analysis and cleaning
2. Tabular data,Unlabled data
3. In pandas rows are-->Indexes, columns are-->Headers


### creating a Data frame
- we can do this by using 2 Dictionaries
- simple dictionary--> DataFrame
- using series

In [25]:
import pandas as pd
import numpy as np
dict1 ={'a':1,'b':2,'c':3,'d':4,'e':5}
dict2 ={'a':5,'b':6,'c':7,'d':8,'f':9}
data={"First":dict1,"Second":dict2}
#now creating a dataframe
df = pd.DataFrame(data,dtype=np.int32)#this is a function in pandas package for creating a dataframe
df

First  Second
a    1.0     5.0
b    2.0     6.0
c    3.0     7.0
d    4.0     8.0
e    5.0     NaN
f    NaN     9.0

In [21]:
# NaN impies Not a Number

In [28]:
#simple dictionary to DataFrame
d1={"name":["preeti","Abc","Efg"],"address":["Hyd","Ts","Ap"]}
df1 = pd.DataFrame(d1)
df1

name address
0  preeti     Hyd
1     Abc      Ts
2     Efg      Ap

In [30]:
#using series -- in pd.Series 'S'shd be in upper case
s1 = pd.Series([1,2,3,4,5,6,7,8,9,10])
s2 = pd.Series([12.23,23.34,45.3,45.5,67.4,34.5,67.8,78.9,87.6,45.6])
s3 = pd.Series(['a','b','c','d','e','f','g','h','i','j'])
data = {"coloumn1":s1,"coloumn2":s2,"coloumn3":s3}
df3 = pd.DataFrame(data)
df3

coloumn1  coloumn2 coloumn3
0         1     12.23        a
1         2     23.34        b
2         3     45.30        c
3         4     45.50        d
4         5     67.40        e
5         6     34.50        f
6         7     67.80        g
7         8     78.90        h
8         9     87.60        i
9        10     45.60        j

In [33]:
#df3.transpose() #it changes headers to indices

### Selecting the data from the DataFrame:
1. loc
2. iloc

In [36]:
#one column
df3["coloumn2"]

0    12.23
1    23.34
2    45.30
3    45.50
4    67.40
5    34.50
6    67.80
7    78.90
8    87.60
9    45.60
Name: coloumn2, dtype: float64

In [37]:
df3[["coloumn2","coloumn3"]]

coloumn2 coloumn3
0     12.23        a
1     23.34        b
2     45.30        c
3     45.50        d
4     67.40        e
5     34.50        f
6     67.80        g
7     78.90        h
8     87.60        i
9     45.60        j

In [39]:
df3.loc[:,"coloumn1"]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: coloumn1, dtype: int64

In [42]:
df3.loc[:,["coloumn1","coloumn2"]]

coloumn1  coloumn2
0         1     12.23
1         2     23.34
2         3     45.30
3         4     45.50
4         5     67.40
5         6     34.50
6         7     67.80
7         8     78.90
8         9     87.60
9        10     45.60

In [43]:
#Extracting multiple coloumn values
df3.loc[0:5,["coloumn1","coloumn2"]]

coloumn1  coloumn2
0         1     12.23
1         2     23.34
2         3     45.30
3         4     45.50
4         5     67.40
5         6     34.50

In [44]:
#for iloc give row and coloumn position

In [48]:
df3.iloc[0:4,0:1]

coloumn1
0         1
1         2
2         3
3         4

### Retrieving the information from DataFrame

In [49]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
coloumn1    10 non-null int64
coloumn2    10 non-null float64
coloumn3    10 non-null object
dtypes: float64(1), int64(1), object(1)
memory usage: 320.0+ bytes


In [50]:
df3.shape

(10, 3)

In [52]:
df3.columns

Index(['coloumn1', 'coloumn2', 'coloumn3'], dtype='object')

In [53]:
df3.index

RangeIndex(start=0, stop=10, step=1)

### Viewing data from DataFrame:
1. head()
2. tail()
3. sample()

In [54]:
df3.head()

coloumn1  coloumn2 coloumn3
0         1     12.23        a
1         2     23.34        b
2         3     45.30        c
3         4     45.50        d
4         5     67.40        e

In [57]:
df3.head(3)

coloumn1  coloumn2 coloumn3
0         1     12.23        a
1         2     23.34        b
2         3     45.30        c

In [55]:
df3.tail()

coloumn1  coloumn2 coloumn3
5         6      34.5        f
6         7      67.8        g
7         8      78.9        h
8         9      87.6        i
9        10      45.6        j

In [56]:
df3.sample()

coloumn1  coloumn2 coloumn3
6         7      67.8        g

In [58]:
df3.sample(2)

coloumn1  coloumn2 coloumn3
3         4      45.5        d
6         7      67.8        g

In [59]:
df3.describe() #gives mean min max count for the columns containg numbers

coloumn1  coloumn2
count  10.00000  10.00000
mean    5.50000  50.81700
std     3.02765  24.26972
min     1.00000  12.23000
25%     3.25000  37.20000
50%     5.50000  45.55000
75%     7.75000  67.70000
max    10.00000  87.60000

In [61]:
#Renaming column headers
df3 = df3.rename(columns={"coloumn1":"First","coloumn2":"Second"})
df3

First  Second coloumn3
0      1   12.23        a
1      2   23.34        b
2      3   45.30        c
3      4   45.50        d
4      5   67.40        e
5      6   34.50        f
6      7   67.80        g
7      8   78.90        h
8      9   87.60        i
9     10   45.60        j

In [62]:
df3.loc[0,:]

First           1
Second      12.23
coloumn3        a
Name: 0, dtype: object

In [63]:
arr1 = np.arange(9).reshape(3,3)

arr1[:,[1,2]] = arr1[:,[2,1]]

print(arr1)

[[0 2 1]
 [3 5 4]
 [6 8 7]]


In [64]:
a=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

b=np.array([[11, 21, 31], [42, 52, 62], [73, 83, 93]])

c=np.append(a,b,axis=1)

print(c)



[[ 1  2  3 11 21 31]
 [ 4  5  6 42 52 62]
 [ 7  8  9 73 83 93]]
